### ISSUE TITLE
Database visual model

### ISSUE THREAD

**Issue by astankowski** [BYTtrio/ADNJO#16]

**Comment by Besiacki** [comment]
Wizualizacja jako tako skończona. W przypadku implementacji nowych funkcji bedzie ona na bieżąco rozszerzana.
Wszelkie uwagi i chęć zmiany proszę zgłaszać do mnie bo tylko ja mam możliwość zmiany diagramu.
_**Typy zmiennych są tylko poglądowe i ich reprezentacja w springu może być zupełnie inna!**_

[Link do wizualnego przedstawienia bazy danych](https://drawsql.app/teams/pjatk-11/diagrams/adnjo)
![Image](https://github.com/user-attachments/assets/ae5fedc9-5261-46d7-a3e6-0ca49322f71f)
